### ISSUE TITLE
Ray ground filter : Spotty ground removal

### ISSUE THREAD

**Issue by MaxandreOgeret** [Autoware-AI/core_perception#55]
### Required information:

- Operating system and version:
- Autoware installation type: Source
- Autoware version or commit hash : `411330c`
- ROS distribution and version: Melodic
- ROS installation type: apt
- Package or library, if applicable: `ray_ground_filter`

### Description of the bug

I have noticed that the `no ground` pointcloud is very sparse and that a lot of points on the obstacles are classified as ground even though they shouldn't.

### Steps to reproduce the bug

- Use `ray_ground_filter` on a high density pointcloud

### Expected behavior

No 'spots' of ground points between vertical points on obvious obstacles.

### Actual behavior

The obstacles are scattered with ground points and vertical points.

### Screenshots

Source of pointcloud : Ouster OS1 128 beams.

- Man at 40m : (Orange = vertical points, grey : raw cloud)  
![image](https://user-images.githubusercontent.com/22786578/114717091-5fc14680-9d3d-11eb-979f-44357781e138.png)

- Man at 3m : (green = ground, pink = vertical)   
![image](https://user-images.githubusercontent.com/22786578/114717039-546e1b00-9d3d-11eb-819b-20835a6ddbad.png)

I have tried to reduce the radial_divider_angle to `0.006` as sensor is running at 1024 samples per rotation and : `(2*PI / 0.006 ≈ 1024)`.

- Man at 40m : (green = ground, pink = vertical)   
![image](https://user-images.githubusercontent.com/22786578/114717411-b038a400-9d3d-11eb-8b07-baa0a430f5b2.png)

- Man at 3m : (green = ground, pink = vertical)   
![image](https://user-images.githubusercontent.com/22786578/114717482-be86c000-9d3d-11eb-98d3-ff3535ce3950.png)

### Additional information

I have tried before and after PR https://github.com/Autoware-AI/core_perception/pull/12 and the result is the same.

Here is the config we use :

```yaml
lidar_center:
  ray_ground_filter:
    base_frame: base_link
    ground_point_topic: /lidar_center/points_ground_test
    input_point_topic: /lidar_center/points_raw
    no_ground_point_topic: /lidar_center/points_no_ground_test
    clipping_height: 1.8
    # min_point_distance in platform_params
    radial_divider_angle: 0.05
    concentric_divider_distance: 0
    local_max_slope: 8
    general_max_slope: 8
    min_height_threshold: 0.4
    reclass_distance_threshold: 0.5
    sensor_height: 2.23
    min_point_distance: 2.0
```

I can provide a bag if needed.

Thanks !
